services:
  mongo:
    image: mongo:6
    container_name: scd-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - scd-mongo-data:/data/db
    networks:
      - scd-net

  backend:
    build:
      context: .             # <-- current directory
      dockerfile: Dockerfile
    container_name: scd-backend
    restart: unless-stopped
    environment:
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongo
    networks:
      - scd-net
    stdin_open: true
    tty: true

volumes:
  scd-mongo-data:

networks:
  scd-net:
    driver: bridge
